#!/bin/bash

killgroup(){
  echo killing...
  kill -INT "$command1PID"
  exit
}
trap "killgroup" EXIT

set -m
cd ocmovies-api
pipenv install
pipenv run python manage.py create_db
pipenv run python manage.py runserver & 
command1PID="$!"
python ../pyserver.py &
jobs
open http://127.0.0.1:5000/templates/home.html
fg % 1
jobs
